### ISSUE TITLE
Building a relational database for Record-on-the-go

### ISSUE THREAD

**Issue by martakutt** [empowerhack/RecordOnTheGo#14]
<img width="799" alt="screen shot 2016-04-10 at 15 09 44" src="https://cloud.githubusercontent.com/assets/16067113/14410928/c25c9a0a-ff32-11e5-99e3-cceb5456a56e.png">

**Comment by jordaneharp** [comment]
We need to figure out if we need a relational database like the one depicted here if we are using Django, which is an object-oriented framework.

**Comment by neraks** [comment]
Closing this issue as a duplicate of #23
